import type { Metadata } from "next";
import "./globals.css";
import ChatBot from "@/components/chat/chat-bot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="min-h-screen">
        {children}
        <ChatBot />
      </body>
    </html>
  );
}
